# Generated by Django 4.2.7 on 2026-01-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataupload',
            options={'ordering': ['-upload_time']},
        ),
        migrations.AddField(
            model_name='dataupload',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='data_type',
            field=models.CharField(choices=[('sensor', 'Sensor Data'), ('log', 'Log Files'), ('metric', 'Metrics'), ('event', 'Event Data'), ('custom', 'Custom Data'), ('csv', 'CSV File'), ('json', 'JSON File'), ('text', 'Text File'), ('image', 'Image File')], default='custom', max_length=50),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='file_path',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
